name: belglow
description: "BelGlow by DigitAlholics"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.6
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/Cyzone/Spring/
    - assets/Cyzone/Summer/
    - assets/Cyzone/Winter/
    - assets/esika/Spring/
    - assets/esika/Summer/
    - assets/esika/Winter/
    - assets/l_bel/Spring/
    - assets/l_bel/Summer/
    - assets/l_bel/Winter/
    - assets/belglow_logo.png
    - assets/lebel.png
    - assets/esika.png
    - assets/cyzone.png
    - assets/perfumes2.jpeg
    - assets/perfumes.jpg
    - assets/fondo.jpeg
    - assets/fondo.png
    - assets/perfume2.png
    - assets/r.jpg